# Generated by Django 4.1.2 on 2023-04-24 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grostore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customers',
        ),
    ]
