# Generated by Django 4.1.2 on 2023-04-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grostore', '0002_delete_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('useraddress', models.TextField(max_length=50)),
                ('usercontact', models.TextField(max_length=50)),
                ('userusername', models.TextField(max_length=50)),
                ('userpassword', models.TextField(max_length=50)),
                ('userconfirmpassword', models.TextField(max_length=50)),
            ],
        ),
    ]
