# Generated by Django 4.1.2 on 2023-04-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grostore', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_registration',
            old_name='useraddress',
            new_name='useremail',
        ),
        migrations.RenameField(
            model_name='user_registration',
            old_name='usercontact',
            new_name='usernumber',
        ),
    ]
