# Generated by Django 4.1.2 on 2023-04-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grostore', '0004_rename_useraddress_user_registration_useremail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_registration',
            new_name='users_registration',
        ),
    ]
