# Generated by Django 4.1.2 on 2023-04-28 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grostore', '0005_rename_user_registration_users_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users_registration',
            old_name='useremail',
            new_name='useraddress',
        ),
        migrations.AddField(
            model_name='users_registration',
            name='userdateofbirth',
            field=models.DateField(null=True),
        ),
    ]
