# Generated by Django 4.1.2 on 2023-04-23 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.TextField(max_length=50)),
                ('customer_email', models.TextField(max_length=50)),
                ('customer_username', models.TextField(max_length=50)),
                ('customer_phonenumber', models.TextField(max_length=50)),
                ('customer_password', models.TextField(max_length=50)),
                ('customer_confirmpassword', models.TextField(max_length=50)),
            ],
        ),
    ]
